# Generated by Django 4.0.5 on 2022-11-15 06:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='party_name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='party',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
